<a href="https://colab.research.google.com/github/humsarika/machine-learning-practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Practice**


In [ ]:
import numpy as np


In [ ]:
mylist = [1,2,3]

In [ ]:
type(mylist)

list

In [ ]:
arr = np.array(mylist)

In [ ]:
matrix = [[1,2,3],[22,33,44]]

In [ ]:
print(matrix)
len(matrix)

[[1, 2, 3], [22, 33, 44]]


2

In [ ]:
np.array(matrix)


array([[ 1,  2,  3],
       [22, 33, 44]])

In [ ]:
np.arange(0,10) # 0 included 10 not included

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,100+1,20) #adding step of 20

array([  0,  20,  40,  60,  80, 100])

In [ ]:
#lets print multiple of 5 using this
np.arange(5,50+1,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
np.zeros(5)
#it will arange 5 zeros, these zeros are floating point number

array([0., 0., 0., 0., 0.])

In [ ]:
#we can create 2d arrays also by providing a size of that 2d array,
# at it will assign 0 to that whole 2d array
np.zeros((3,4))  #rows = 3,cols = 4


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.linspace(2,20,10) #linspace returns evenly spaced numbers in the given interval

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [ ]:
np.eye(4) #it will give a identity matrix of 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
print(np.random.rand(3,2)) #it willgive 3x2 random numbers between  0 and 1, where 3 is rowand 2 is cols
print(np.random.rand(3)) #it will give 3 random numbers between  0 and 1

[[0.23326827 0.84556399]
 [0.56311139 0.68212352]
 [0.8924658  0.81189641]]
[0.26807326 0.999716   0.39060484]


In [ ]:
np.random.randn(5)#return samples from standard normal distribution

array([-0.48736612,  1.13011908, -2.03773849,  0.35746465,  0.96770804])

In [ ]:
np.random.randn(2,4)#return samples from standard normal distribution

# values closer to 0 are more likely to appear than the values farther from 0.

array([[-0.91185514,  0.21344268, -0.18549522,  0.0871682 ],
       [-0.46614859, -0.13244767,  0.09102008,  1.38456851]])

In [ ]:
np.random.randint(1,10,4)
# return 4 randon integer values in the given range,
# where a lower value is 1(inclusive) and the higher value is 10 (exclusive),
# and it takes a parameter size which tells how many random values it will give

array([5, 4, 9, 6])

In [ ]:
np.random.randint(20,50, (2,3)) #in 2d array

array([[20, 43, 20],
       [33, 20, 47]])

In [ ]:
np.random.seed(42) # it particularly set of random numbers
np.random.rand(4)
# as long as the seed is same the
# if run it in different device or cell it will give same random number

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(42) # it particularly set of random numbers
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
ages = np.random.randint(1,100,10)

In [ ]:
ages

array([83, 87, 75, 75, 88, 24,  3, 22, 53,  2])

In [ ]:
maxage = ages.max()
print(maxage)

88


In [ ]:
minage = ages.min()
print(minage)

2


In [ ]:
ages.argmax()

4

In [ ]:
ages.argmin()

9

In [ ]:
ages.dtype # dtype is attribute not a method call

dtype('int64')

In [ ]:
ages.shape #shape is attribute not a method call

(10,)

In [ ]:
ages.reshape(2,5)

array([[83, 87, 75, 75, 88],
       [24,  3, 22, 53,  2]])

In [ ]:
# Create an array of 10 fives
np.ones(10) * 5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Create an array of the integers from 10 to 50
np.arange(10,50+1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Create an array of all the even integers from 10 to 50
np.arange(10,50+1,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.61065893])

In [ ]:
#  Use NumPy to generate an array of 25 random numbers
# sampled from a standard normal distribution
np.random.randn(25)

array([-1.34861804,  0.95796384,  0.54957249,  0.36402509,  0.36414801,
       -0.20191559,  0.8942308 , -0.91991251, -0.9945422 , -0.55768831,
       -1.62850924,  0.02385753,  0.01222587, -2.10218229, -0.79355782,
        0.71530001,  1.11855269, -2.19024477,  0.00796141, -0.13842634,
        0.92434193,  0.45778934,  0.96616352,  0.03428519,  0.69857466])

Create below matrix


In [ ]:
# array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
#        [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
#        [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
#        [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
#        [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
#        [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
#        [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
#        [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
#        [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
#        [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

arr=np.arange(0,100)/100
arr.reshape(10,10)


array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [ ]:
# Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Write code that reproduces the output shown below
mat[2:,1:]



array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# get the sum of all the values in mat
mat.sum()

325

In [ ]:
# get the standard deviation of the values in mat
mat.std()

7.211102550927978

In [ ]:
# get the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])