<a href="https://colab.research.google.com/github/sarika-kushwaha/data-science-colab-notebook/blob/main/udemyPythonCrashCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Basics of Python**

In [ ]:
def power(x,a):
    print(x**a)
power(7,4)

2401


In [ ]:
a = "Sarika kush"

In [ ]:
li = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(li[3][1][2][0])
print(li[3][1][2])

hello
['hello']


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
def isThereDog(str1,word):
   return word in str1


In [ ]:
str1 = "Is There a Dog here:"
str2 = str1.lower()
w1 = "dog"
w2 = w1.lower()
print(isThereDog(str2,w2))

1


In [ ]:
str3 = "Is There a dog dog here:" # find out is there any substring = "dog" is here
str3.count("dog")

2

In [ ]:
def caught(speed,isbirthday):
   if isbirthday is True:
      speed = speed - 5

   if speed<=60:
        print("No ticket")
   elif speed > 61 and speed < 81:
        print("Small Ticket")
   elif speed > 81:
        print("Big Ticket")

caught(34,True)
caught(74,False)
caught(80,True)

No ticket
Small Ticket
Small Ticket


### **NUMPY:**

In [ ]:
import numpy as np


In [ ]:
np.zeros(4) # creates a array of zero of size 4 

array([0., 0., 0., 0.])

In [ ]:
np.ones(5)  # creates a array of 1's of size 5 

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,6,3)

array([0., 3., 6.])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(4)# gives 4 random number between 0 and 1

array([0.31982289, 0.28402447, 0.49872378, 0.18063919])

In [ ]:
np.random.randn(2)

array([ 0.7677607 , -0.14723689])

In [ ]:
np.random.randint(100) #returns a random number between 0 - 100

96

In [ ]:
np.random.randint(20,100,5) #returns 5 random number between 20 - 100 and 100 is eclusive in range

array([69, 73, 93, 28, 72])

In [ ]:
np.random.seed(40)#to generate different random numbers everytime
np.random.rand(4)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

In [ ]:
arr = np.arange(0,10) # create a array of of size 10 and assign the elements from 0 to 10-1

In [ ]:
arr=np.random.randint(0,101,10)# generate 10 random integer in range of 0 to 101, where 101 is exclusive
arr

array([30, 79, 14, 92, 58, 74, 22,  3, 91, 99])

In [ ]:
myarr = np.linspace(0,10,101) #generate 101 evenly spaced numbers in range of 0 to 10 and structured as numpy array
print(myarr)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [ ]:
myarr[0:7]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [ ]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr[:5] #prints element of array from 0 to 5 (exclusive) |arr[m:n] here m is the number which denotes the beginning and n shows that where to stop

array([0, 1, 2, 3, 4])

In [ ]:
arr[:4] = 100 # assigns value 100  from index 0 to 4 which means arr[0] ,arr[1] ,arr[2] ,arr[3] = 100

In [ ]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
slice_of_arr = arr[:6] # creates a slice of array (elements including from index 0 to 6)
slice_of_arr

array([100, 100, 100, 100,   4,   5])

In [ ]:
arr_copy = arr.copy()# creates a copy of array "arr"
arr_copy

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
arr2d = [1,2,3,[23,43,[22,12],[2,3]],32]

[1,2,3,[23,43,[22,12],[2,3]],32]
x = [23,43,[22,12],[2,3]]
[1,2,3,x,32]
y= [22,12]
z =[2,3]
x = [23,43,y,z]

In [ ]:
arr2d[3][3][0]

2

In [ ]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
dice_rolls_over_two = dice_rolls>2
print(dice_rolls_over_two)

[ True False  True False  True False False  True False  True False False
  True  True  True  True  True False  True False  True  True  True  True
 False  True  True  True  True]


In [ ]:
dice_rolls[dice_rolls_over_two]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [ ]:
import numpy as np
arr = np.array([3, 1, 5,0, -2, 5, 0,-5, 3, 4, 5, 2, 4, -2, 6, 6, -3, 6, -2, 3, 5, 6, 5])
arr1 = np.array(3)
print(arr1)
new_arr = len(arr[arr <0])
print(arr[0])
new_arr

IndexError: ignored

In [ ]:
arr1 = np.arange(0,10)
print(arr1+5)
print(arr1-3)

[ 5  6  7  8  9 10 11 12 13 14]
[-3 -2 -1  0  1  2  3  4  5  6]


In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 - arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr1/ arr1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.sum(arr1)

45

In [ ]:
np.max(arr1)

9

In [ ]:
np.min(arr1)

0

In [ ]:
np.var(arr1)

8.25

In [ ]:
np.std(arr1)

2.8722813232690143

In [ ]:
np.mean(arr1)

4.5

In [ ]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr2 = np.arange(0,16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr2.shape

(4, 4)

In [ ]:
arr2.sum(axis=0) #sum wrt rows

array([24, 28, 32, 36])

In [ ]:
arr2.sum(axis=1) # sum wrt columns

array([ 6, 22, 38, 54])

In [ ]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_total = account_transactions.sum() # or account_total = np.sum(account_transactions)
account_total

2720

In [ ]:
ar1 = np.zeros(10)
ar1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
ar2 = np.ones(10)
ar2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ar3 = np.zeros(10)
ar3+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand()#generating random number between 0 and 1

array([0.4030557 , 0.97076164])

In [ ]:
np.random.randn(25)

array([-0.79268573,  0.41820829,  1.26610334,  0.05186567,  0.12421447,
        0.6849905 ,  0.72126581, -0.41591939,  0.36264587,  0.07758641,
        0.54528953,  0.06887244,  2.15345011,  1.08334839, -0.86948384,
       -0.64707579,  2.1915145 ,  0.21342932, -1.50659193, -1.83956465,
        1.46648526, -1.20683932, -2.73175927,  0.03713161,  0.7067834 ])

In [ ]:
np.linspace(0,1,101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
array = np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
array[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
array[3][4]

20

In [ ]:
array[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
array[4]

array([21, 22, 23, 24, 25])

In [ ]:
array[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
array.sum()

325

In [ ]:
array.std()

7.211102550927978

In [ ]:
array.sum(axis = 0)#rows -> axis =0

array([55, 60, 65, 70, 75])